# Generated by Django 3.2.9 on 2021-11-13 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211113_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 18, 12, 4, 730485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surveys',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 11, 13, 18, 12, 4, 730485, tzinfo=utc)),
        ),
    ]
