# Generated by Django 3.2.9 on 2021-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211113_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date_start',
            field=models.DateField(),
        ),
    ]
