# Generated by Django 3.2.9 on 2021-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211113_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyreport',
            name='user',
            field=models.BigIntegerField(default=1, verbose_name='id пользователя'),
            preserve_default=False,
        ),
    ]
