# Generated by Django 3.2.9 on 2021-11-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_surveyreport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='ответ пользователя')),
                ('chosen_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.defaultanswer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.question')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.surveyreport')),
            ],
        ),
    ]
