# Generated by Django 3.2.9 on 2021-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.TextField(null=True, verbose_name='ответ пользователя'),
        ),
    ]
